-- mysql < batch-file > mysql.out
CREATE DATABASE thermaldb;
USE thermaldb;
CREATE TABLE IF NOT EXISTS `temp_data` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_time` DATETIME NULL DEFAULT NULL,
  `measured_temp` FLOAT DEFAULT NULL,
  PRIMARY KEY (`id`)
) CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `humi_data` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_time` DATETIME NULL DEFAULT NULL,
  `measured_humi` FLOAT DEFAULT NULL,
  PRIMARY KEY (`id`)
) CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `co2_data` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_time` DATETIME NULL DEFAULT NULL,
  `measured_co2` FLOAT DEFAULT NULL,
  PRIMARY KEY (`id`)
) CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `dust_data` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_time` DATETIME NULL DEFAULT NULL,
  `measured_dust` FLOAT DEFAULT NULL,
  `PM1_0` FLOAT DEFAULT NULL,
  `PM2_5` FLOAT DEFAULT NULL,
  `PM10_0` FLOAT DEFAULT NULL,
  `PM1_0_ATM` FLOAT DEFAULT NULL,
  `PM2_5_ATM` FLOAT DEFAULT NULL,
  `PM10_0_ATM` FLOAT DEFAULT NULL,
  `PCNT_0_3` FLOAT DEFAULT NULL,
  `PCNT_0_5` FLOAT DEFAULT NULL,
  `PCNT_1_0` FLOAT DEFAULT NULL,
  `PCNT_2_5` FLOAT DEFAULT NULL,
  `PCNT_5_0` FLOAT DEFAULT NULL,
  `PCNT_10_0` FLOAT DEFAULT NULL,
  PRIMARY KEY (`id`)
) CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `pres_data` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_time` DATETIME NULL DEFAULT NULL,
  `measured_pres` FLOAT DEFAULT NULL,
  PRIMARY KEY (`id`)
) CHARSET=utf8;
SHOW TABLES;
DESC dust_data;
QUIT